





const TICKET_STATUSES = Object.freeze({
  NEW: 'NEW',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
})

const STATUSES = Object.freeze(['NEW', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED'])




const TICKET_FLOW = Object.freeze({
  [TICKET_STATUSES.NEW]: [TICKET_STATUSES.ASSIGNED, TICKET_STATUSES.IN_PROGRESS, TICKET_STATUSES.RESOLVED],
  [TICKET_STATUSES.ASSIGNED]: [TICKET_STATUSES.IN_PROGRESS, TICKET_STATUSES.RESOLVED, TICKET_STATUSES.NEW],
  [TICKET_STATUSES.IN_PROGRESS]: [TICKET_STATUSES.RESOLVED, TICKET_STATUSES.NEW],
  [TICKET_STATUSES.RESOLVED]: [TICKET_STATUSES.IN_PROGRESS, TICKET_STATUSES.NEW],
})

const PRIORITIES = Object.freeze(['LOW', 'MEDIUM', 'HIGH'])

const CATEGORIES = Object.freeze([
  'Account',
  'Billing',
  'Technical',
  'Feature Request',
  'Bug',
  'Other',
])

const ROLES = Object.freeze({
  CUSTOMER: 'customer',
  AGENT: 'agent',
  ADMIN: 'admin',
})

const TICKET_NUMBER_PREFIX = 'SFL'

const TICKET_NUMBER_SEQ = 'tickets'

module.exports = {
  TICKET_STATUSES,
  STATUSES,
  TICKET_FLOW,
  PRIORITIES,
  CATEGORIES,
  ROLES,
  TICKET_NUMBER_PREFIX,
  TICKET_NUMBER_SEQ,
}